name: FLEXFORCE API

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
 staging:
   name: FLEXFORCE API
   runs-on: ubuntu-latest
   steps:
    - name: deploying to server
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FLEXFORCE_SERVER }}
        username: ${{ secrets.FLEXFORCE_USER }}
        key: ${{ secrets.FLEXFORCE_KEYS }}
        port: ${{ secrets.FLEXFORCE_PORT }}
        script: |
          cd /usr/flexforce-project/flexforce-api/
          sudo git pull origin main
          sudo docker build -t flex-force-api .
          sudo docker rm -f flex-force-api || true
          sudo docker run --name flex-force-api -d -p 8080:8080 --restart always flex-force-api
